# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opsbudget < Formula
  desc "CLI for Ping by OpsBudget — uptime monitoring"
  homepage "https://opsbudget.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getopsbudget/opsbudget-cli/releases/download/v0.1.2/opsbudget_darwin_amd64.tar.gz"
      sha256 "2f061d5cd2abd0efd6597c10aefad8e79830d893d7b30f7c21c7bcd293151336"

      define_method(:install) do
        bin.install "opsbudget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getopsbudget/opsbudget-cli/releases/download/v0.1.2/opsbudget_darwin_arm64.tar.gz"
      sha256 "e3511d76ebf4e75ffe43323f7b92b92fd6d3cb8741fcfb386908be8d13e22cbf"

      define_method(:install) do
        bin.install "opsbudget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getopsbudget/opsbudget-cli/releases/download/v0.1.2/opsbudget_linux_amd64.tar.gz"
      sha256 "405a3d96201cfc63a0da70cabd2877aed40bab3f9358bc6b388c854c5cfd1d64"
      define_method(:install) do
        bin.install "opsbudget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getopsbudget/opsbudget-cli/releases/download/v0.1.2/opsbudget_linux_arm64.tar.gz"
      sha256 "2390db705cb7599bee89bfd2e26b1466d4580762816b9aa39f03374d2c12efa8"
      define_method(:install) do
        bin.install "opsbudget"
      end
    end
  end
end
